name: backend-ci
on:
  push:
    branches: [ main ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt
      - run: . .venv/bin/activate && python -c "import fastapi,uvicorn; print('ok')"
